// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibejltntfexvnwwjqbts.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZWpsdG50ZmV4dm53d2pxYnRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNTA2NzcsImV4cCI6MjA2MzcyNjY3N30.AlSshBLhkeayNGXPaFP0RRT_VbbpT6Ogjq0uiDc0byE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);